"""first init

Revision ID: 85266e86e51a
Revises: 
Create Date: 2025-05-20 22:06:25.631459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue

# revision identifiers, used by Alembic.
revision = '85266e86e51a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Uuid(), server_default=FetchedValue(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('previous_password', sa.String(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.Column('user_avatar_url', sa.String(), nullable=True),
                    sa.Column('role', sa.Enum('AGENT', 'CLIENT', 'ADMIN', name='userrole'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('deleted_by', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('users_created_by_foreign')),
                    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('users_deleted_by_foreign')),
                    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('users_updated_by_foreign')),
                    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
                    )
    op.create_index(op.f('users_email_index'), 'users', ['email'], unique=True)
    op.create_table('listings',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('property_type', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('deleted_by', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('listings_created_by_foreign')),
                    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('listings_deleted_by_foreign')),
                    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('listings_updated_by_foreign')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('listings_user_id_foreign')),
                    sa.PrimaryKeyConstraint('id', name=op.f('listings_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    op.drop_index(op.f('users_email_index'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
