"""remove user_id

Revision ID: a5b1ef5ad922
Revises: 85266e86e51a
Create Date: 2025-05-28 22:49:18.185211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b1ef5ad922'
down_revision = '85266e86e51a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listings_user_id_foreign', 'listings', type_='foreignkey')
    op.drop_column('listings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('listings_user_id_foreign', 'listings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
