"""New tables attachments and listing_attachment

Revision ID: c9421bf5178d
Revises: a5b1ef5ad922
Create Date: 2025-06-07 15:43:58.915691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9421bf5178d'
down_revision = 'a5b1ef5ad922'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('attachments_created_by_foreign')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('attachments_deleted_by_foreign')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('attachments_updated_by_foreign')),
    sa.PrimaryKeyConstraint('id', name=op.f('attachments_pkey'))
    )
    op.create_table('listings_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('listings_attachments_attachment_id_foreign')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('listings_attachments_created_by_foreign')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('listings_attachments_deleted_by_foreign')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('listings_attachments_listing_id_foreign')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('listings_attachments_updated_by_foreign')),
    sa.PrimaryKeyConstraint('id', name=op.f('listings_attachments_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings_attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
