"""add column to attachment

Revision ID: bf87ff1f94ad
Revises: c9421bf5178d
Create Date: 2025-06-07 16:03:45.305120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf87ff1f94ad'
down_revision = 'c9421bf5178d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'hash')
    # ### end Alembic commands ###
